import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Sparkles,
    ShieldCheck,
    TrendingUp,
    Calendar,
    Clock,
    CheckCircle2,
    XCircle,
    Eye,
    BarChart3,
    Zap,
    MoreHorizontal,
    ArrowUpRight
} from 'lucide-react';

const ContentHub = () => {
    const [activeTab, setActiveTab] = useState('authority');

    // Mock Data for Content Approval
    const [pendingApprovals, setPendingApprovals] = useState([
        {
            id: 'cont_1',
            title: 'Q1 Sourdough Masterclass Series',
            channel: 'Instagram Reels',
            strategy: 'Educational Authority',
            roi: '+32% Reach Est.',
            status: 'pending',
            details: 'A 5-part series focusing on long-fermentation techniques. Generated by ContentStrategistAgent.',
            draftUrl: '#'
        },
        {
            id: 'cont_2',
            title: 'The Science of Crisp Crust',
            channel: 'YouTube Shorts',
            strategy: 'Product Showcase',
            roi: '+15% Conversion Est.',
            status: 'pending',
            details: 'High-energy vertical video showcasing the "crunch" factor. Generated by VisualAgent.',
            draftUrl: '#'
        }
    ]);

    const stats = [
        { label: "Content Reach", value: "1.2M", trend: "+12.5%", icon: Eye, color: "text-blue-600" },
        { label: "Engagement Rate", value: "4.8%", trend: "+0.3%", icon: Zap, color: "text-emerald-600" },
        { label: "Conversion ROI", value: "18.2%", trend: "+2.1%", icon: TrendingUp, color: "text-indigo-600" }
    ];

    const handleApprove = (id) => {
        setPendingApprovals(prev => prev.map(item => item.id === id ? { ...item, status: 'approved' } : item));
    };

    const handleReject = (id) => {
        setPendingApprovals(prev => prev.filter(item => item.id !== id));
    };

    return (
        <div className="p-8 max-w-7xl mx-auto space-y-8">
            {/* Header */}
            <header className="flex flex-col md:flex-row md:items-center justify-between gap-6">
                <div>
                    <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">Content Intelligence Hub</h1>
                    <p className="text-slate-500 font-medium">Authorizing and optimizing autonomous content operations</p>
                </div>
                <div className="flex gap-3">
                    <button className="px-4 py-2 bg-white border border-slate-200 rounded-xl text-sm font-bold text-slate-700 hover:bg-slate-50 transition-colors flex items-center gap-2">
                        <Calendar size={16} /> Schedule
                    </button>
                    <button className="px-4 py-2 bg-indigo-600 rounded-xl text-sm font-bold text-white hover:bg-indigo-700 shadow-lg shadow-indigo-200 transition-colors flex items-center gap-2">
                        <Sparkles size={16} /> Generate Strategy
                    </button>
                </div>
            </header>

            {/* Tactical Stats */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {stats.map((stat, i) => (
                    <motion.div
                        key={i}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: i * 0.1 }}
                        className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm"
                    >
                        <div className="flex justify-between items-start mb-4">
                            <div className={`p-2 rounded-lg bg-slate-50 ${stat.color}`}>
                                <stat.icon size={20} />
                            </div>
                            <span className="text-xs font-bold text-emerald-600 bg-emerald-50 px-2 py-1 rounded-full uppercase tracking-wider">
                                {stat.trend}
                            </span>
                        </div>
                        <h3 className="text-3xl font-black text-slate-900 leading-none mb-2">{stat.value}</h3>
                        <p className="text-sm font-bold text-slate-400 uppercase tracking-widest">{stat.label}</p>
                    </motion.div>
                ))}
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* Authority Board */}
                <section className="lg:col-span-2 space-y-6">
                    <div className="flex items-center justify-between">
                        <h2 className="text-xl font-bold flex items-center gap-2">
                            <ShieldCheck className="text-indigo-600" size={24} /> Authority Board
                        </h2>
                        <div className="flex bg-slate-100 p-1 rounded-xl">
                            <button
                                onClick={() => setActiveTab('authority')}
                                className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${activeTab === 'authority' ? 'bg-white shadow-sm text-indigo-600' : 'text-slate-500'}`}
                            >
                                Pending Review
                            </button>
                            <button
                                onClick={() => setActiveTab('scheduled')}
                                className={`px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${activeTab === 'scheduled' ? 'bg-white shadow-sm text-indigo-600' : 'text-slate-500'}`}
                            >
                                Scheduled
                            </button>
                        </div>
                    </div>

                    <div className="space-y-4">
                        {pendingApprovals.filter(a => a.status === 'pending').map((item) => (
                            <motion.div
                                key={item.id}
                                layout
                                initial={{ opacity: 0, scale: 0.95 }}
                                animate={{ opacity: 1, scale: 1 }}
                                className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm hover:border-indigo-200 transition-all group"
                            >
                                <div className="p-6">
                                    <div className="flex justify-between items-start mb-4">
                                        <div>
                                            <div className="flex items-center gap-2 mb-1">
                                                <span className="px-2 py-0.5 bg-indigo-50 text-indigo-600 text-[10px] font-black rounded uppercase tracking-wider border border-indigo-100">
                                                    {item.channel}
                                                </span>
                                                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">• {item.strategy}</span>
                                            </div>
                                            <h4 className="text-lg font-bold text-slate-900 group-hover:text-indigo-600 transition-colors">{item.title}</h4>
                                        </div>
                                        <div className="text-right">
                                            <p className="text-xs font-black text-emerald-600">{item.roi}</p>
                                            <p className="text-[10px] text-slate-400 font-bold uppercase">Confidence</p>
                                        </div>
                                    </div>
                                    <p className="text-sm text-slate-600 leading-relaxed mb-6 italic border-l-2 border-slate-100 pl-4">
                                        "{item.details}"
                                    </p>
                                    <div className="flex items-center justify-between pt-4 border-t border-slate-50">
                                        <button className="text-slate-500 hover:text-indigo-600 text-xs font-bold flex items-center gap-2 transition-colors">
                                            <Eye size={14} /> Preview Draft
                                        </button>
                                        <div className="flex gap-2">
                                            <button
                                                onClick={() => handleReject(item.id)}
                                                className="p-2 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded-xl transition-all"
                                            >
                                                <XCircle size={20} />
                                            </button>
                                            <button
                                                onClick={() => handleApprove(item.id)}
                                                className="px-6 py-2 bg-indigo-600 text-white rounded-xl text-xs font-bold hover:bg-emerald-600 transition-all flex items-center gap-2 shadow-lg shadow-indigo-100"
                                            >
                                                <ShieldCheck size={16} /> Authorize Execution
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </motion.div>
                        ))}
                    </div>
                </section>

                {/* Performance Analytics Sidebar */}
                <aside className="space-y-6">
                    <section className="bg-slate-900 text-white p-6 rounded-2xl shadow-xl">
                        <h2 className="text-lg font-bold flex items-center gap-2 mb-6">
                            <BarChart3 className="text-indigo-400" size={20} /> Channel Health
                        </h2>
                        <div className="space-y-4">
                            {[
                                { name: "Instagram", score: 88, color: "bg-gradient-to-r from-purple-500 to-pink-500" },
                                { name: "YouTube", score: 72, color: "bg-red-500" },
                                { name: "Email", score: 94, color: "bg-emerald-500" }
                            ].map((channel, i) => (
                                <div key={i} className="space-y-2">
                                    <div className="flex justify-between text-xs font-bold">
                                        <span className="text-slate-400 uppercase tracking-widest">{channel.name}</span>
                                        <span>{channel.score}%</span>
                                    </div>
                                    <div className="h-1.5 w-full bg-slate-800 rounded-full overflow-hidden">
                                        <motion.div
                                            initial={{ width: 0 }}
                                            animate={{ width: `${channel.score}%` }}
                                            transition={{ delay: 0.5 + i * 0.1, duration: 1 }}
                                            className={`h-full ${channel.color}`}
                                        />
                                    </div>
                                </div>
                            ))}
                        </div>
                    </section>

                    <section className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm overflow-hidden relative">
                        <div className="absolute top-0 right-0 p-4">
                            <ArrowUpRight size={24} className="text-emerald-500 opacity-20" />
                        </div>
                        <h2 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                            <TrendingUp className="text-indigo-600" size={20} /> Best Performers
                        </h2>
                        <div className="space-y-4">
                            <div className="p-4 rounded-xl bg-slate-50 border border-slate-100">
                                <h5 className="text-xs font-black text-slate-800 uppercase mb-1">Top Reel</h5>
                                <p className="text-sm text-slate-600 font-medium">"5 Sourdough Mistakes"</p>
                                <div className="mt-2 text-[10px] font-bold text-emerald-600 flex items-center gap-1">
                                    <Activity size={10} /> Viral Velocity: High
                                </div>
                            </div>
                        </div>
                    </section>
                </aside>
            </div>
        </div>
    );
};

export default ContentHub;
