"""Add trial columns to user

Revision ID: 8403163a3c78
Revises: d1010af6aab4
Create Date: 2026-06-07 15:38:10.564328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8403163a3c78'
down_revision: Union[str, Sequence[str], None] = 'd1010af6aab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('user_accounts', sa.Column('trial_started_at', sa.DateTime(), nullable=True))
    op.add_column('user_accounts', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'trial_ends_at')
    op.drop_column('user_accounts', 'trial_started_at')
    op.drop_column('user_accounts', 'subscription_status')
    # ### end Alembic commands ###
