"""funnel builder hosted pages

Revision ID: 84ca8ea25419
Revises: ec8cb9e668b0
Create Date: 2026-06-27 09:27:19.466921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84ca8ea25419'
down_revision: Union[str, Sequence[str], None] = 'ec8cb9e668b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosted_pages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('page_type', sa.String(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=True),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.Column('nurture_sequence_id', sa.String(), nullable=True),
    sa.Column('thank_you_message', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('content_item_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('submissions', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('style_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id')
    )
    op.create_index(op.f('ix_hosted_pages_slug'), 'hosted_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_hosted_pages_user_id'), 'hosted_pages', ['user_id'], unique=False)
    op.create_index('ix_hosted_pages_user_status', 'hosted_pages', ['user_id', 'status'], unique=False)
    op.create_table('form_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('page_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('ip_country', sa.String(), nullable=True),
    sa.Column('utm_source', sa.String(), nullable=True),
    sa.Column('utm_medium', sa.String(), nullable=True),
    sa.Column('utm_campaign', sa.String(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['hosted_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submissions_page_id'), 'form_submissions', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_submissions_page_id'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index('ix_hosted_pages_user_status', table_name='hosted_pages')
    op.drop_index(op.f('ix_hosted_pages_user_id'), table_name='hosted_pages')
    op.drop_index(op.f('ix_hosted_pages_slug'), table_name='hosted_pages')
    op.drop_table('hosted_pages')
    # ### end Alembic commands ###
