"""Add data column to customer_journeys

Revision ID: dd9d9f191e3c
Revises: 4a0fa8c681d5
Create Date: 2026-03-27 09:43:44.146316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd9d9f191e3c'
down_revision: Union[str, Sequence[str], None] = '4a0fa8c681d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_journeys', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_journeys', 'data')
    # ### end Alembic commands ###
