"""sync db schema with models

Revision ID: ee0961280bdf
Revises: 794ba8671dca
Create Date: 2026-06-06 17:45:51.177970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee0961280bdf'
down_revision: Union[str, Sequence[str], None] = '794ba8671dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_event_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('how', sa.Text(), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_event_records_agent_id'), 'agent_event_records', ['agent_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('source_platform', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pattern_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('learned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connected_integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('oauth_tokens_encrypted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('source_platform', sa.String(), nullable=True),
    sa.Column('source_content_id', sa.String(), nullable=True),
    sa.Column('icp_score', sa.Float(), nullable=True),
    sa.Column('engagement_level', sa.String(), nullable=True),
    sa.Column('pipeline_stage', sa.String(), nullable=True),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('performance_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_metric', sa.String(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('process_recording', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('embedded_at', sa.DateTime(), nullable=True),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nurture_sequences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('paystack_id', sa.String(), nullable=True),
    sa.Column('token_budget', sa.Integer(), nullable=True),
    sa.Column('tokens_used_month', sa.Integer(), nullable=True),
    sa.Column('content_count_month', sa.Integer(), nullable=True),
    sa.Column('video_count_month', sa.Integer(), nullable=True),
    sa.Column('billing_cycle_start', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('token_usage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_name', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_tokens', sa.Integer(), nullable=True),
    sa.Column('actual_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('reached_at', sa.DateTime(), nullable=True),
    sa.Column('process_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repeatable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project_milestones')
    op.drop_table('projects')
    op.drop_table('agent_events')
    op.drop_table('action_outcomes')
    op.drop_table('user_preferences')
    op.drop_table('learned_patterns')
    op.drop_table('agent_authorizations')
    op.drop_table('adaptive_learning_signals')
    op.drop_index(op.f('ix_conversation_history_session_id'), table_name='conversation_history')
    op.drop_table('conversation_history')
    op.drop_table('agent_triggers')
    op.drop_table('ai_action_outcomes')
    op.drop_table('agent_outputs')
    op.drop_table('llm_usage_records')
    op.drop_table('integration_credentials')
    op.add_column('business_identities', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('business_identities', sa.Column('target_audience', sa.Text(), nullable=True))
    op.add_column('business_identities', sa.Column('icp', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('business_identities', sa.Column('brand_visual', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('business_identities', sa.Column('brand_story', sa.Text(), nullable=True))
    op.add_column('business_identities', sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('business_identities', sa.Column('pricing_strategy', sa.Text(), nullable=True))
    op.add_column('business_identities', sa.Column('marketing_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('business_identities', sa.Column('content_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('business_identities', sa.Column('goals_3month', sa.Text(), nullable=True))
    op.add_column('business_identities', sa.Column('goals_12month', sa.Text(), nullable=True))
    op.add_column('business_identities', sa.Column('challenges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('business_identities', sa.Column('completion_percentage', sa.Float(), nullable=True))
    op.alter_column('business_identities', 'business_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('business_identities', 'brand_voice',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using="COALESCE(NULLIF(brand_voice, ''), '{}')::jsonb",
               existing_nullable=True)
    op.create_unique_constraint(None, 'business_identities', ['user_id'])
    op.drop_column('business_identities', 'core_objectives')
    op.drop_column('business_identities', 'icp_description')
    op.drop_column('business_identities', 'brand_tone')
    op.drop_column('business_identities', 'budget_limit')
    op.add_column('customer_journeys', sa.Column('stage', sa.String(), nullable=True))
    op.add_column('customer_journeys', sa.Column('health_score', sa.Float(), nullable=True))
    op.add_column('customer_journeys', sa.Column('conversion_probability', sa.Float(), nullable=True))
    op.add_column('customer_journeys', sa.Column('churn_risk', sa.Float(), nullable=True))
    op.add_column('customer_journeys', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('customer_journeys', 'status')
    op.drop_column('customer_journeys', 'segment')
    op.add_column('media_assets', sa.Column('user_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_media_assets_user_id'), table_name='media_assets')
    op.create_index(op.f('ix_media_assets_user_id'), 'media_assets', ['user_id'], unique=False)
    op.drop_constraint(op.f('media_assets_user_accounts.id_fkey'), 'media_assets', type_='foreignkey')
    op.create_foreign_key(None, 'media_assets', 'user_accounts', ['user_id'], ['id'])
    op.drop_column('media_assets', 'user_accounts.id')
    op.add_column('user_accounts', sa.Column('firebase_uid', sa.String(), nullable=True))
    op.add_column('user_accounts', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user_accounts', sa.Column('role', sa.String(), nullable=True))
    op.add_column('user_accounts', sa.Column('subscription_tier', sa.String(), nullable=True))
    op.add_column('user_accounts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_accounts_firebase_uid'), 'user_accounts', ['firebase_uid'], unique=True)
    op.drop_column('user_accounts', 'hashed_password')
    op.drop_column('user_accounts', 'tier')
    op.add_column('workflow_executions', sa.Column('workflow_id', sa.String(), nullable=True))
    op.add_column('workflow_executions', sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_executions', sa.Column('transparency_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_executions', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('workflow_executions', sa.Column('total_cost', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'workflow_executions', 'workflows', ['workflow_id'], ['id'])
    op.drop_column('workflow_executions', 'workflow_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_executions', sa.Column('workflow_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workflow_executions', type_='foreignkey')
    op.drop_column('workflow_executions', 'total_cost')
    op.drop_column('workflow_executions', 'total_tokens')
    op.drop_column('workflow_executions', 'transparency_log')
    op.drop_column('workflow_executions', 'results')
    op.drop_column('workflow_executions', 'workflow_id')
    op.add_column('user_accounts', sa.Column('tier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_accounts', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_accounts_firebase_uid'), table_name='user_accounts')
    op.drop_column('user_accounts', 'updated_at')
    op.drop_column('user_accounts', 'subscription_tier')
    op.drop_column('user_accounts', 'role')
    op.drop_column('user_accounts', 'name')
    op.drop_column('user_accounts', 'firebase_uid')
    op.add_column('media_assets', sa.Column('user_accounts.id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'media_assets', type_='foreignkey')
    op.create_foreign_key(op.f('media_assets_user_accounts.id_fkey'), 'media_assets', 'user_accounts', ['user_accounts.id'], ['id'])
    op.drop_index(op.f('ix_media_assets_user_id'), table_name='media_assets')
    op.create_index(op.f('ix_media_assets_user_id'), 'media_assets', ['user_accounts.id'], unique=False)
    op.drop_column('media_assets', 'user_id')
    op.add_column('customer_journeys', sa.Column('segment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer_journeys', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customer_journeys', 'updated_at')
    op.drop_column('customer_journeys', 'churn_risk')
    op.drop_column('customer_journeys', 'conversion_probability')
    op.drop_column('customer_journeys', 'health_score')
    op.drop_column('customer_journeys', 'stage')
    op.add_column('business_identities', sa.Column('budget_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('business_identities', sa.Column('brand_tone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('business_identities', sa.Column('icp_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('business_identities', sa.Column('core_objectives', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'business_identities', type_='unique')
    op.alter_column('business_identities', 'brand_voice',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('business_identities', 'business_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('business_identities', 'completion_percentage')
    op.drop_column('business_identities', 'challenges')
    op.drop_column('business_identities', 'goals_12month')
    op.drop_column('business_identities', 'goals_3month')
    op.drop_column('business_identities', 'content_preferences')
    op.drop_column('business_identities', 'marketing_channels')
    op.drop_column('business_identities', 'pricing_strategy')
    op.drop_column('business_identities', 'competitors')
    op.drop_column('business_identities', 'brand_story')
    op.drop_column('business_identities', 'brand_visual')
    op.drop_column('business_identities', 'icp')
    op.drop_column('business_identities', 'target_audience')
    op.drop_column('business_identities', 'industry')
    op.create_table('integration_credentials',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('integration_credentials_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('integration_credentials_pkey'))
    )
    op.create_table('llm_usage_records',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('llm_usage_records_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_usage_records_pkey'))
    )
    op.create_table('project_milestones',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_milestones_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_milestones_pkey'))
    )
    op.create_table('agent_outputs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_intent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('agent_outputs_user_id_fkey')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], name=op.f('agent_outputs_workflow_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_outputs_pkey'))
    )
    op.create_table('ai_action_outcomes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('score', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('ai_action_outcomes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_action_outcomes_pkey'))
    )
    op.create_table('agent_triggers',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('intent', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('agent_triggers_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_triggers_pkey'))
    )
    op.create_table('conversation_history',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('conversation_history_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_history_pkey'))
    )
    op.create_index(op.f('ix_conversation_history_session_id'), 'conversation_history', ['session_id'], unique=False)
    op.create_table('adaptive_learning_signals',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pattern', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('adaptive_learning_signals_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('adaptive_learning_signals_pkey'))
    )
    op.create_table('agent_authorizations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('agent_authorizations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_authorizations_pkey'))
    )
    op.create_table('learned_patterns',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('insight', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recommendation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('supporting_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sample_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('learned_patterns_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('learned_patterns_pkey'))
    )
    op.create_table('projects',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('projects_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rule', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rule_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('signal_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], name=op.f('user_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey'))
    )
    op.create_table('action_outcomes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('journey_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['customer_journeys.id'], name=op.f('action_outcomes_journey_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('action_outcomes_pkey'))
    )
    op.create_table('agent_events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('workflow_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('how', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('why', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_events_pkey'))
    )
    op.drop_table('milestones')
    op.drop_table('messages')
    op.drop_table('interactions')
    op.drop_table('workflows')
    op.drop_table('token_usage')
    op.drop_table('subscriptions')
    op.drop_table('nurture_sequences')
    op.drop_table('knowledge_documents')
    op.drop_table('goals')
    op.drop_table('conversations')
    op.drop_table('content_templates')
    op.drop_table('content_items')
    op.drop_table('contacts')
    op.drop_table('connected_integrations')
    op.drop_table('campaigns')
    op.drop_table('calendar_patterns')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_agent_event_records_agent_id'), table_name='agent_event_records')
    op.drop_table('agent_event_records')
    # ### end Alembic commands ###
